### ISSUE TITLE
Support for PMP, DMP, and Ex Nihilo 2

### ISSUE THREAD

**Issue by InkDragon** [mezz/JEIAddons#12]
Could you add support for Ex Nihilo 2, Plants Mega Pack, and Decoration Mega Pack?

I'm not sure about Ex Nihilo 2, but I know PMP/DMP's author has no plans to add support for JEI.

**Comment by MaegnusTheBlackMage** [comment]
Would love to see more mods supported, just requested Minestrappolation in issue #16

**Comment by mezz** [comment]
Sorry but I do not intend to add support for more mods. When this started, I didn't know if mods would support JEI. It has done well, and modders do not have a hard time adding support themselves.
