### ISSUE TITLE
Minestrappolation Support

### ISSUE THREAD

**Issue by MaegnusTheBlackMage** [mezz/JEIAddons#16]
minestrappolation is a cool mod that removes a lot of vanilla recipes and adds there own new ones without any clear indication of how to craft things using the new recipes. I would love to see support for this mod added to the game as they currently do not have JEI support built in.

**Comment by mezz** [comment]
Sorry but I do not intend to add support for more mods. When this started, I didn't know if mods would support JEI. It has done well, and modders do not have a hard time adding support themselves.
