### ISSUE TITLE
JEI 2.12.0 not working?

### ISSUE THREAD

**Issue by Sasikaa** [mezz/JEIAddons#3]
The NEWEST JEI 2.12.0 mod working on 1.8.8.

The JEIaddons mod is not working the new JEI mod? Why?
Please make the update, because not working the NEI, and other recipe mod the 1.8.8

**Comment by mezz** [comment]
JEIaddons is only for 1.8 right now, because that's the version Thaumcraft is on. It doesn't have support for any other mods yet, so there's no reason for a 1.8.8 version right now.

Just remove JEIaddons and it will work fine.

**Comment by Sasikaa** [comment]
Not work fine! The other mod recipes not working fine.
Example: The TechReborn mod some recipes not showing, some recipes not. This is the MOD bug, or any, or JEI?
Sorry my BAD englisg, i'm hungarian, and not speak english...

**Comment by mezz** [comment]
1.8.8 is very new, the mods are still broken and there is no integration yet.
The mods with no recipes need to add integration with JEI, or I need to add it in JEIAddons.
I am working to make sure more mods show their special recipes in JEI.

**Comment by Sasikaa** [comment]
The 1.8.8 version is NOT working the JEI addons...

**Comment by mezz** [comment]
Yes, JeiAddons is for 1.8.

**Comment by mezz** [comment]
Thaumcraft updated to 1.8.9, so JEIAddons has updated too.
http://minecraft.curseforge.com/projects/jeiaddons
