### ISSUE TITLE
World Reload Required for recently researched items to appear in JEI

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JEIAddons#7]
Title pretty much says it all - anytime I unlock a new recipe in research ('Require Thaumcraft Research' = True), I have to reload my world / re-log in order for the item to appear in JEI at all.

I'm sure it's just a matter of updating JEI when I complete a research entry. Last I heard, there's nothing fired on Thaumcraft's API end for when I right click on the discovery - but you can always use the sound played event to re-poll the player's currently unlocked research.

Or, it could be none of this, and you already know exactly what it is and I'm just rambling on.

Anyways.
:heart: your work :D

**Comment by mezz** [comment]
The research requirement is a bit hacky/buggy right now, so I have it disabled by default.
I made a request here https://github.com/Azanor/thaumcraft-5-api/issues/6 which would make the feature work better. Until that's in, I recommend keeping 'Require Thaumcraft Research' false.

**Comment by mezz** [comment]
I have completely disabled the 'Require Thaumcraft Research' feature for now.

**Comment by mezz** [comment]
I decided to go about this a different way, and just show all recipes and mark the ones that are not researched.
![2016-02-04_17 14 36](https://cloud.githubusercontent.com/assets/916092/12835209/07714964-cb63-11e5-99aa-d9735fac49ad.png)

**Comment by oitsjustjose** [comment]
Beautiful!
