### ISSUE TITLE
Crash with Just a Few Fish, Thaumcraft and JEI Addons

### ISSUE THREAD

**Issue by sweetsosweet** [mezz/JEIAddons#9]
Hi, I'm getting a crash when I add JEI Addons to a world with [Just a Few Fish](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2508671-just-a-few-fish-version-1-3) mod, and Thaumcraft loaded. [Here is my crash report.](http://pastebin.com/9Wi79DcW)

Any help on this issue would be appreciated, thanks!

**Comment by mezz** [comment]
Thanks for the report!
The crash log doesn't show any problem related to functions of JEIAddons, I think it may be coincidental.
I recommend reporting to Just a Few Fish, they may know more.
